### Create Product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product Test",
  "desc": "the best product in the world!",
  "price": 100.50,
  "quantity": 10
}

### Get All Products
GET http://localhost:8080/products

### Get Product by ID (Replace `{product_id}` with a valid product ID)
GET http://localhost:8080/products/64ced82fd90ece5d0904ac3d

### Update Product by ID (Replace `{product_id}` with a valid product ID)
PUT http://localhost:8080/products/{product_id}
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 150.25,
  "quantity": 20
}

### Delete Product by ID (Replace `{product_id}` with a valid product ID)
DELETE http://localhost:8080/products/64cedb39cb066a6a11c6aed9

### Create User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "sumet",
  "email": "test",
  "password": "1234",
  "role": "admin"
}

### Login
POST   http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test",
  "password": "1234"
}

### Validate
GET http://localhost:8080/auth/validate
