### Test 123

### Create Product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product B",
  "price": 100.50,
  "quantity": 10
}

### Get All Products
GET http://localhost:8080/products

### Get Product by ID (Replace `{product_id}` with a valid product ID)
GET http://localhost:8080/products/64ced82fd90ece5d0904ac3d

### Update Product by ID (Replace `{product_id}` with a valid product ID)
PUT http://localhost:8080/products/{product_id}
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 150.25,
  "quantity": 20
}

### Delete Product by ID (Replace `{product_id}` with a valid product ID)
DELETE http://localhost:8080/products/64cedb39cb066a6a11c6aed9
